name: my_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
