name: traceme
description: App to help find missing or speech-impaired persons
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ‘‡ Supabase (Auth + Storage + Database)
  supabase_flutter: ^2.5.9

  # ðŸ‘‡ For image upload & HTTP requests
  image_picker: ^1.1.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg.jpg
    - assets/images/bg_index.jpg
